apiVersion: v1
kind: Secret
metadata:
  name: {{ include "conduit-relay.fullname" . }}
  labels:
    {{- include "conduit-relay.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.env.CONDUIT_JWT_SECRET }}
  CONDUIT_JWT_SECRET: {{ .Values.env.CONDUIT_JWT_SECRET | b64enc | quote }}
  {{- else }}
  {{- fail "env.CONDUIT_JWT_SECRET is required. Set it with --set env.CONDUIT_JWT_SECRET=..." }}
  {{- end }}
  {{- if .Values.env.RELAY_REGISTRATION_TOKEN }}
  RELAY_REGISTRATION_TOKEN: {{ .Values.env.RELAY_REGISTRATION_TOKEN | b64enc | quote }}
  {{- end }}
